# Site
name: "Tout nouveau, tout beau !"
description: "Partage de mes aventures dans le monde de la création textile"
sub-description: "Couture à la main, machine à coudre et surjeteuse - Tricot - Broderie - Travaux manuels"
meta_description: "Blog, création de vêtements et accessoires, patrons, coffrets de naissance, Tout nouveau, tout beau !, couture, tutoriels, boutique, Aline Delvallé"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl:
google_analytics: 'UA-132326218-1'
disqus: 'toutnouveautoutbeau'
mailchimp-list: 'https://toutnouveautoutbeau.us20.list-manage.com/subscribe/post?u=c9482545a69f95d98c9c065e6&amp;id=3131b25ba7'
include: ["_pages"]
permalink: /:title/
# Authors
authors:
  aline:
    name: Aline Delvallé
    display_name: Aline
    gravatar: 0ec26da97a064b0cd49555d9ee0da48f
    email: aline@toutnouveautoutbeau.fr
    web: https://www.instagram.com/aline_delvalle
    instagram: https://www.instagram.com/aline_delvalle
    description: "Créatrice de vêtements et accessoires, se spécialisant dans la création de patrons accessibles pour tous. Créatrice de la boutique 'Tout nouveau, tout beau !'"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
