version: '2'
services:
  site:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --config  _config.yml,_config.docker.yml --livereload --force_polling --incremental
    image: jekyll/jekyll:3
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729

